COMMONOBJS		= kugfile.o kugerr.o
KUGITEROBJS		= kugiter.o
LSKUGOBJS		= lskug.o
EXKUGOBJS		= exkug.o
PKKUGOBJS		= pkkug.o
GEOKUGOBJS		= geokug.o
LSKUG			= lskug
EXKUG			= exkug
PKKUG			= pkkug
GEOKUG			= geokug

CFLAGS		= -pedantic -Wall -Wextra -std=gnu99 -ggdb
#CFLAGS		= -pedantic -Wall -Wextra -std=gnu99 
LDFLAGS		= 

all:			$(LSKUG) $(EXKUG) $(PKKUG) $(GEOKUG)

$(LSKUG):		$(COMMONOBJS) $(LSKUGOBJS) $(KUGITEROBJS)
	$(CC) $(LDFLAGS) -o $(LSKUG) $(COMMONOBJS) $(LSKUGOBJS) $(KUGITEROBJS)

$(EXKUG):		$(COMMONOBJS) $(EXKUGOBJS) $(KUGITEROBJS)
	$(CC) $(LDFLAGS) -o $(EXKUG) $(COMMONOBJS) $(EXKUGOBJS) $(KUGITEROBJS)

$(PKKUG):		$(COMMONOBJS) $(PKKUGOBJS)
	$(CC) $(LDFLAGS) -o $(PKKUG) $(COMMONOBJS) $(PKKUGOBJS)

$(GEOKUG):		$(COMMONOBJS) $(GEOKUGOBJS)
	$(CC) $(LDFLAGS) -o $(GEOKUG) $(COMMONOBJS) $(GEOKUGOBJS)

clean:
	rm -f  $(COMMONOBJS) $(LSKUGOBJS) $(EXKUGOBJS) $(PKKUGOBJS) $(GEOKUGOBJS) $(LSKUG) $(EXKUG) $(PKKUG) $(GEOKUG) $(KUGITEROBJS)

.PHONY: clean
